// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestsendingemailTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testsendingemail() {
    // Test name: Test sending email
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://localhost:8081/");
    // 2 | setWindowSize | 822x843 | 
    driver.manage().window().setSize(new Dimension(822, 843));
    // 3 | click | id=email | 
    driver.findElement(By.id("email")).click();
    // 4 | type | id=email | aiman.ab.ghapar@gmail.com
    driver.findElement(By.id("email")).sendKeys("aiman.ab.ghapar@gmail.com");
    // 5 | click | id=message | 
    driver.findElement(By.id("message")).click();
    // 6 | type | id=message | Test email sent
    driver.findElement(By.id("message")).sendKeys("Test email sent");
    // 7 | click | css=button | 
    driver.findElement(By.cssSelector("button")).click();
    // 8 | click | css=html | 
    driver.findElement(By.cssSelector("html")).click();
    // 9 | close |  | 
    driver.close();
  }
}
